# base image: https://hub.docker.com/_/node

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/repo
    working_dir: /repo/src
    ports:
      - "3000:3000"
    # 対話的コンテナのための設定
    tty: true
    stdin_open: true

  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    volumes:
      - .:/repo
    working_dir: /repo/script/deploy
    # 対話的コンテナのための設定
    tty: true
    stdin_open: true
    profiles: ["deploy"]
    # クレデンシャルの環境変数による引き渡し設定
    env_file:
      - .env
    # セキュリティ強化のための制限
    security_opt:
      - no-new-privileges:true
    cap_drop: 
      - ALL
    read_only: true
    tmpfs:
      - /tmp
