# base image: https://hub.docker.com/_/node

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./src:/src
      - ./script:/script/dev:ro
    # 対話的コンテナのための設定
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]

  deploy:
    build:
      context: .
      dockerfile: Dockerfile-deploy
    volumes:
      - ./src:/src:ro
      - ./script:/script/deploy:ro
    # 対話的コンテナのための設定
    tty: true
    stdin_open: true
    command: ["sleep", "infinity"]
    profiles: ["deploy"]
    # クレデンシャルの環境変数による引き渡し設定
    env_file:
      - .env
    environment:
      - CLOUDFLARE_API_TOKEN
      - CLOUDFLARE_ACCOUNT_ID
    # セキュリティ強化のための制限
    security_opt:
      - no-new-privileges:true
    cap_drop: 
      - ALL
    read_only: true
    tmpfs:
      - /tmp
